import { Phase } from '@/types/trading';

export const PHASES: Phase[] = [
  {
    id: 1,
    title: 'Market Orientation',
    subtitle: 'You will understand what price movement means and execute your first trade with intention.',
    desc: 'Place your first buy and sell. Learn price, profit, and loss basics.',
    ariaIntroMessage: "Welcome to TradeSchool. I'm ARIA — your AI trading coach. This chart shows real price action, candle by candle. Each green bar means price rose. Each red bar means price fell. Your job right now: place a BUY trade and close it. That's it. Let's begin.",
    conceptToTeach: 'Price movement and trade execution',
    chartAnnotations: ['patternHighlight'],
    challenge: {
      title: 'Your First Trade',
      description: 'Open and close a BUY trade.',
      instruction: 'Click BUY to enter a long position, watch the price move, then close it.',
      criteria: { tradeType: 'buy', count: 1 },
      xpReward: 50,
      failureMessage: "You closed without a BUY trade completing. Open a BUY, then close it to complete this challenge.",
      successMessage: "Trade executed and closed. You now understand the basic loop: enter, hold, exit. That's all trading is — everything else is just refining the when.",
    },
    unlocksFeatures: ['basicTrade'],
    requiredXP: 50,
  },
  {
    id: 2,
    title: 'Candlestick Reading',
    subtitle: 'You will decode the language of price through candle anatomy and learn what buyers and sellers are telling you.',
    desc: 'Understand candle anatomy, wicks, and rejection signals.',
    ariaIntroMessage: "Every candle tells a story. The body shows who won — buyers or sellers. The wicks show who tried and failed. A long upper wick means sellers pushed price back down. A long lower wick means buyers defended. Learn to read this language and you'll understand the market's intentions before they play out.",
    conceptToTeach: 'Candle anatomy: body, wicks, and what they reveal',
    chartAnnotations: ['patternHighlight'],
    challenge: {
      title: 'Read the Rejection',
      description: 'Close a trade after holding it for at least 3 candles.',
      instruction: 'Open a trade and hold it through at least 3 new candles before closing.',
      criteria: { count: 1 },
      xpReward: 75,
      failureMessage: "You closed too quickly. Hold your position through at least 3 candles to observe how price develops.",
      successMessage: "You held your position and watched candles form in real time. That patience is a skill most traders never develop.",
    },
    unlocksFeatures: ['candleTooltip'],
    requiredXP: 150,
  },
  {
    id: 3,
    title: 'Trend Recognition',
    subtitle: 'You will learn to identify the market\'s dominant direction and never fight the trend again.',
    desc: 'Identify uptrends and downtrends before trading.',
    ariaIntroMessage: "An uptrend is a series of higher highs and higher lows. A downtrend is lower highs and lower lows. Trading with the trend doubles your probability of success before you even enter a trade. Look at the chart now — which direction is price making higher moves? Trade in that direction.",
    conceptToTeach: 'Higher High / Higher Low structure and trend direction',
    chartAnnotations: ['swingPoints', 'trendLine'],
    challenge: {
      title: 'Trade With the Trend',
      description: 'Open a BUY trade during an uptrend and close it in profit.',
      instruction: 'Wait for an uptrend (higher highs), then BUY. Close it for a profit.',
      criteria: { tradeType: 'buy', mustBeProfit: true, count: 1 },
      xpReward: 100,
      failureMessage: "The trade didn't close in profit, or you entered against the trend. Wait for clear upward momentum before buying.",
      successMessage: "Trading with the trend. This is the foundation everything else is built on. Never forget this lesson.",
    },
    unlocksFeatures: ['swingPointAnnotations'],
    requiredXP: 300,
  },
  {
    id: 4,
    title: 'Support & Resistance',
    subtitle: 'You will discover the invisible walls that control price and learn to trade them with precision.',
    desc: 'Trade bounces off key horizontal price levels.',
    ariaIntroMessage: "Support and resistance are price levels where the market has repeatedly reversed. Support is the floor — buyers defend it. Resistance is the ceiling — sellers attack it. I've marked both zones on your chart. Your edge: buy near support, sell near resistance. These levels work because thousands of traders are watching the same lines.",
    conceptToTeach: 'Support and resistance zones as trade entry locations',
    chartAnnotations: ['srZones'],
    challenge: {
      title: 'Bounce Trade',
      description: 'Open a trade near a support or resistance level.',
      instruction: 'Watch for price to approach the support zone, then BUY. Set a stop loss below support.',
      criteria: { requireStopLoss: true, count: 1 },
      xpReward: 125,
      failureMessage: "You need a stop loss set for this challenge. S/R trading without a stop loss below support is gambling, not trading.",
      successMessage: "You identified a level, entered near it, and protected yourself with a stop. That's professional trade structure.",
    },
    unlocksFeatures: ['srZones', 'stopLoss'],
    requiredXP: 500,
  },
  {
    id: 5,
    title: 'Entry Timing',
    subtitle: 'You will stop entering too early and learn to wait for confirmation before risking capital.',
    desc: 'Wait for confirmation before entering trades.',
    ariaIntroMessage: "Most traders lose money not because they pick the wrong direction — but because they enter too early. Confirmation means waiting for price to show you it's ready to move. A breakout candle with a strong close. A rejection wick forming. A return to a broken level. Enter on evidence, not prediction.",
    conceptToTeach: 'Trade entry confirmation and patience',
    chartAnnotations: ['patternHighlight', 'srZones'],
    challenge: {
      title: 'Confirmed Entry',
      description: 'Enter a trade with both a stop loss and take profit set.',
      instruction: 'Set SL and TP before entering. The ratio must be at least 1.5:1 reward to risk.',
      criteria: { requireStopLoss: true, requireTakeProfit: true, minRR: 1.5, count: 1 },
      xpReward: 150,
      failureMessage: "You need both a stop loss and take profit with at least 1.5:1 R:R. Plan your trade before entering — always.",
      successMessage: "Planned entry, planned exit, planned risk. This is what separates traders from gamblers.",
    },
    unlocksFeatures: ['takeProfit', 'rrDisplay'],
    requiredXP: 750,
  },
  {
    id: 6,
    title: 'Risk Management',
    subtitle: 'You will master the one skill that keeps professional traders alive: controlling how much you lose.',
    desc: 'Master stop losses, position sizing, and take profits.',
    ariaIntroMessage: "Here's the truth about trading: everyone loses. Winners just lose less than they make. Risk management is the difference between a blown account and a long career. Risk no more than 1% of your balance on any single trade. Use a stop loss every time. This isn't optional — it's the rule that keeps you in the game.",
    conceptToTeach: 'Position sizing and the 1% risk rule',
    chartAnnotations: ['srZones'],
    challenge: {
      title: 'Disciplined Risk',
      description: 'Execute 3 trades, each with a stop loss and risk under 2% of balance.',
      instruction: 'Use the lot size slider to keep risk under 2%. Set a stop loss on every trade.',
      criteria: { requireStopLoss: true, maxRiskPercent: 2, count: 3 },
      xpReward: 200,
      failureMessage: "Not all trades had proper risk management. Every single trade needs a stop loss with risk under 2%.",
      successMessage: "Three disciplined trades. You're building the habits that compound into a long career.",
    },
    unlocksFeatures: ['riskPercent', 'lotSizeSlider'],
    requiredXP: 1100,
  },
  {
    id: 7,
    title: 'EMA Confluence',
    subtitle: 'You will add the most powerful trend-following tool to your arsenal and stop trading blind.',
    desc: 'Use EMA 9/21 to identify trend direction and entry points.',
    ariaIntroMessage: "The EMA — Exponential Moving Average — is a dynamic support and resistance line that follows price. EMA 9 is fast, EMA 21 is slow. When fast crosses above slow: uptrend. When fast crosses below: downtrend. Trade in the direction of the cross, enter on pullbacks to the EMAs. This filters out 70% of bad trades.",
    conceptToTeach: 'EMA 9/21 crossover as trend filter',
    chartAnnotations: ['emaLines', 'trendLine'],
    challenge: {
      title: 'EMA Confluence Trade',
      description: 'Enter a BUY when EMA 9 is above EMA 21, with a stop loss.',
      instruction: 'Wait for uptrend conditions (price above both EMAs), then buy with a stop loss.',
      criteria: { tradeType: 'buy', requireStopLoss: true, mustBeProfit: true, count: 1 },
      xpReward: 175,
      failureMessage: "Trade with the EMA trend direction and set a stop loss. The EMAs are your compass — don't ignore them.",
      successMessage: "EMA confluence confirmed your entry. This is indicator-assisted trading done correctly.",
    },
    unlocksFeatures: ['ema9', 'ema21'],
    requiredXP: 1500,
  },
  {
    id: 8,
    title: 'RSI Divergence',
    subtitle: 'You will learn to see what price hides — momentum shifts before they happen.',
    desc: 'Use RSI to spot momentum shifts and divergence setups.',
    ariaIntroMessage: "RSI measures momentum, not just price. When price makes a new high but RSI makes a lower high — that's bearish divergence. The move is running out of steam. Divergence doesn't mean reverse immediately — it means the conviction is weakening. Use it to tighten your stop or avoid new entries in the same direction.",
    conceptToTeach: 'RSI divergence as momentum warning signal',
    chartAnnotations: ['srZones', 'patternHighlight'],
    challenge: {
      title: 'Momentum Awareness',
      description: 'Complete 2 profitable trades with stop losses set.',
      instruction: 'Focus on trade quality over speed. Both trades must close in profit with SL protection.',
      criteria: { requireStopLoss: true, mustBeProfit: true, count: 2 },
      xpReward: 200,
      failureMessage: "Both trades need to close profitably with stop losses. Quality over quantity.",
      successMessage: "Two profitable, protected trades. Your momentum awareness is developing. This is how pros build consistency.",
    },
    unlocksFeatures: ['rsi'],
    requiredXP: 2000,
  },
  {
    id: 9,
    title: 'Breakout Trading',
    subtitle: 'You will learn to catch the biggest moves in the market by trading at the moment of maximum conviction.',
    desc: 'Identify and trade genuine breakouts with volume confirmation.',
    ariaIntroMessage: "Breakouts happen when price smashes through a resistance level with force. The key word is 'force' — volume must confirm. High volume breakout = real move. Low volume breakout = likely trap. Watch the volume bars: if the breakout candle has 2x normal volume, that breakout has conviction. Enter on the retest of the broken level.",
    conceptToTeach: 'Breakout identification and volume confirmation',
    chartAnnotations: ['srZones', 'patternHighlight'],
    challenge: {
      title: 'Breakout Entry',
      description: 'Catch a breakout move with a 2:1 R:R and stop loss.',
      instruction: 'Enter during a breakout with stop below the broken level. Target 2x your stop distance.',
      criteria: { requireStopLoss: true, requireTakeProfit: true, minRR: 2, count: 1 },
      xpReward: 225,
      failureMessage: "Need a 2:1 R:R minimum on a breakout entry with a stop loss. Don't enter without a plan.",
      successMessage: "Breakout caught with proper risk management. This setup, done consistently, builds accounts.",
    },
    unlocksFeatures: ['breakoutAlert'],
    requiredXP: 2800,
  },
  {
    id: 10,
    title: 'Range Trading',
    subtitle: 'You will profit in sideways markets when trend traders sit on their hands wondering what to do.',
    desc: 'Trade bounces within a defined price range.',
    ariaIntroMessage: "Markets trend only 30% of the time. The other 70%? They range. Range traders buy support and sell resistance, collecting small gains while trend traders wait. The trap is confusing a range breakout for a continuation. If price breaks out of the range with volume, get out. Inside the range, fade the extremes.",
    conceptToTeach: 'Range identification and fade trading at extremes',
    chartAnnotations: ['srZones'],
    challenge: {
      title: 'Range Fade',
      description: 'Execute 2 profitable range bounce trades.',
      instruction: 'Buy near support, sell near resistance. Both trades must close in profit.',
      criteria: { mustBeProfit: true, requireStopLoss: true, count: 2 },
      xpReward: 225,
      failureMessage: "Both trades need to close in profit with stop losses. Trade the range boundaries — not the middle.",
      successMessage: "Two profitable range trades. You've expanded your toolkit to profit in any market condition.",
    },
    unlocksFeatures: ['rangeDetection'],
    requiredXP: 3800,
  },
  {
    id: 11,
    title: 'Trade Psychology',
    subtitle: 'You will conquer the emotional triggers that destroy accounts and trade like the machine you need to become.',
    desc: 'Conquer revenge trading, FOMO, and emotional decision-making.',
    ariaIntroMessage: "This is the hardest phase. Not because the concepts are complex — but because they require you to override instinct. Revenge trading: entering after a loss to 'make it back.' FOMO: chasing a move that already happened. Overconfidence: sizing up after a win streak. I'll call all of these out in real time. Your job: listen and stop.",
    conceptToTeach: 'Emotional pattern recognition and discipline under pressure',
    chartAnnotations: ['patternHighlight'],
    challenge: {
      title: 'Disciplined Session',
      description: 'Complete 5 trades with stop losses, no revenge trading detected.',
      instruction: 'Trade calmly. Set a stop loss on every trade. Do not enter again within 30 seconds of a loss.',
      criteria: { requireStopLoss: true, count: 5 },
      xpReward: 300,
      failureMessage: "Revenge trading or missing stop losses detected. Reset. Take a breath. Every trade is independent.",
      successMessage: "Five disciplined trades with no revenge trading. This is the mindset that keeps professionals in the game for decades.",
    },
    unlocksFeatures: ['revengeTradingDetection', 'cooldown'],
    requiredXP: 5000,
  },
  {
    id: 12,
    title: 'Pro Simulation',
    subtitle: 'You will trade like a professional — combining every tool, every concept, and every lesson into a unified strategy.',
    desc: 'Full professional simulation with all tools unlocked.',
    ariaIntroMessage: "You've reached the final phase. Every tool is unlocked. I'll step back and let you trade. My commentary will be less frequent — but I'm still watching. Prove you can combine trend analysis, S/R levels, EMA confluence, proper risk management, and emotional discipline into a consistent strategy. This is the real thing.",
    conceptToTeach: 'Full strategy integration and consistent execution',
    chartAnnotations: ['swingPoints', 'trendLine', 'srZones', 'emaLines'],
    challenge: {
      title: 'Pro Performance',
      description: 'Achieve a 60%+ win rate over 10 trades with proper risk management.',
      instruction: 'Complete 10 trades. Win at least 6. Use stop losses on all of them. Keep risk under 2%.',
      criteria: { requireStopLoss: true, maxRiskPercent: 2, count: 10 },
      xpReward: 500,
      failureMessage: "Not enough discipline or win rate. Review your entries — are you trading with the trend and from key levels?",
      successMessage: "Professional-grade performance. You've completed TradeSchool. The market is your classroom now.",
    },
    unlocksFeatures: ['allFeatures'],
    requiredXP: 8000,
  },
];

export function getPhase(id: number): Phase {
  return PHASES.find(p => p.id === id) || PHASES[0];
}

export function getNextPhase(currentId: number): Phase | null {
  return PHASES.find(p => p.id === currentId + 1) || null;
}
